backend:
  name: git-gateway
  repo: dovbush-media/dovbush-media.github.io # Твій репозиторій
  branch: main

media_folder: "assets/images" # Куди будуть падати картинки, якщо завантажиш з компа
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Пости про ігри"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата публікації", name: "date", widget: "datetime"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Головна картинка (URL)", name: "image", widget: "string"}
      - {label: "Категорія", name: "category", widget: "select", options: ["Знижки", "Новини", "Огляди"]}
      - {label: "Текст поста", name: "body", widget: "markdown"} # ОЦЕ ТВІЙ WORD
